
export const types = {
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_SUCCCESS: 'GET_POSTS_SUCCCESS',
    GET_POSTS_ERROR: 'GET_POSTS_ERROR',
    LIKE_POST: 'LIKE_POST',
    LIKE_POSTS_SUCCCESS: 'LIKE_POSTS_SUCCCESS',
    LIKE_POSTS_ERROR: 'LIKE_POSTS_ERROR',

    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCCESS: 'LOGIN_USER_SUCCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',   
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCCESS: 'REGISTER_USER_SUCCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    LOGOUT: 'LOGOUT',
    
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR' 
}
